---
title: "data_prep"
format: html
---

```{r, echo=FALSE, results='hide'}
library(ayuda)
```

Raw data location folder
```{r}
pick2_dir <- file.path("/home", whoami(), "data", "raw", "pick2")
pick2 <- leer(pick2_dir)
pick2$list()
```
Connect to a Postgres database
```{r}
pg <- leer("postgres", database="postgres", port=5432, host="postgres", user="postgres")$con()
```
Create a new database
```{sql connection=pg}
CREATE DATABASE pick2;
```
Remove connection
```{r}
rm(pg)
```
Connect to the new database
```{r}
con <- leer("pick2", database="postgres", port=5432, host="postgres", user="postgres")

for (file in list.files(pick2_dir, full.names = TRUE)){
  print(file) 
  con$write_chunked(file,
                  db_args=list(overwrite = TRUE) )
} 
con$list()
```


```{r}
basics <- con$leer("title_basics") %>% 
  filter(titleType == "movie") %>% 
  mutate(year= as.numeric(na_if(startYear, "\\N")),
         dur=as.numeric(na_if(runtimeMinutes, "\\N")),
         genres=ifelse(genres == "\\N", "", genres )) %>% 
  # filter(year>=1990) %>%
  # summarise(n=n( ), mean=mean(dur, na.rm = TRUE), min=min(dur, na.rm = TRUE), max=max(dur, na.rm = TRUE)) %>% 
  filter(dur>1000) %>% 
  collect()

basics %>% glimpse()
```

